# Base configs
baseurl: "https://pmgolait.github.io"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Sketches"
subtitle: ""
author: "Pratyush Golait"
header:
 title: "Sketches"
 subtitle: "by Pratyush"
footer:
 name: "Every Sketch Tells a Story"
 bio: "A glimpse into the emotions that words can't capture.
 A good sketch is better than a long speech.. but I'm absolutely terrible at this. So, just enjoy the chaos!"
# web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/pratyushgolait"
  github: "https://github.com/pmgolait"
  linkedin: "https://linkedin.com/in/pratyushgolait"